Id: Nt.Requirements
Name: Nt.Requirements
Publisher: novacom software gmbh
AppMoniker: NtRequirements
Version: 1.0.0
License: MIT
Description: PowerShell-Skript für die Installation von Softwareanforderungen.
Homepage: https://github.com/cgassner1000/Nt.Requirements
